add initial ttl language
vcstuff/draft-ietf-oauth-status-list pull request #101
Opened 2024-02-17 09:27 UTC by tplooker

Alternative to #49 as it had gone stale.

2024-02-17 10:49 UTC, paulbastian approved these changes

2024-02-17 12:15 UTC, c2bo requested changes

2024-02-17 12:15 UTC, c2bo commented on draft-ietf-oauth-status-list.md
> +
This section should be moved up to line ~450where "status" is defined for JWT

2024-02-17 12:18 UTC, c2bo commented on draft-ietf-oauth-status-list.md
> +* `ttl`: OPTIONAL. The `ttl` (time to live) claim, if present, MUST specify the maximum amount of time, in seconds, that the Status List Token may be cached by a consumer before a fresh copy is retri
```suggestion
* `ttl`: OPTIONAL. The `ttl` (time to live) claim, if present, MUST specify the maximum amount of time, in seconds, that the Status List Token may be cached by a consumer before a fresh copy is retrieved. The value of the claim MUST be a positive number.
```

2024-02-17 12:19 UTC, c2bo commented on draft-ietf-oauth-status-list.md
> +in the Status List Token provides one mechanism for setting a maximum cache time for the fetched data. This property permits distribution of
```suggestion
in the Status List Token provides one mechanism for setting a maximum cache time for the fetched data. This property permits distribution of
```

2024-02-17 12:19 UTC, c2bo commented on draft-ietf-oauth-status-list.md
> +a status list to a CDN or other distribution mechanism while giving guidance to consumers of the status list on how often they need to fetch
```suggestion
a status list to a CDN or other distribution mechanism while giving guidance to consumers of the status list on how often they need to fetch
```

2024-02-20 07:51 UTC, tplooker commented on draft-ietf-oauth-status-list.md
> +* `ttl`: OPTIONAL. The `ttl` (time to live) claim, if present, MUST specify the maximum amount of time, in seconds, that the Status List Token may be cached by a consumer before a fresh copy is retri
```suggestion
* `ttl`: OPTIONAL. The `ttl` (time to live) claim, if present, MUST specify the maximum amount of time, in seconds, that the Status List Token can be cached by a consumer before a fresh copy SHOULD be retrieved. The value of the claim MUST be a positive number.
```

2024-02-27 10:18 UTC, c2bo commented
I moved the claim registration up - we have to do CWT registration after the CBOR/CWT PR has been merged - i'll create an issue for this

2024-02-27 10:22 UTC, c2bo approved these changes

2024-02-27 19:40 UTC, merged