improve privacy consideration to recommend re-issuance
vcstuff/draft-ietf-oauth-status-list pull request #105
Opened 2024-02-19 21:56 UTC by paulbastian

Closes # 

## 📑 Description

## Preview Link

[click here for rendered preview of PR](https://github.com/<repo-name>/<branch-name>/<draft-name>.html)

2024-02-21 20:01 UTC, c2bo requested changes

2024-02-22 08:07 UTC, paulbastian commented on draft-ietf-oauth-status-list.md
> +Referenced Tokens may be regularly re-issued to increase security or to mitigate linkability and prevent tracking by Relying Parties. In this case, every Referenced Token MUST have a fresh Status Lis
I thought about this as well, but we also have a similar consideration in place for batch-issuance and we mandate separate indices with MUST there as well

2024-02-24 18:25 UTC, c2bo approved these changes

2024-02-24 18:26 UTC, c2bo commented on draft-ietf-oauth-status-list.md
> +Referenced Tokens may be regularly re-issued to increase security or to mitigate linkability and prevent tracking by Relying Parties. In this case, every Referenced Token MUST have a fresh Status Lis
Let's revisit this point again later on but you are right - this seems to be consistent with the rest of the draft right now

2024-03-03 09:48 UTC, tplooker commented on draft-ietf-oauth-status-list.md
> +## Unobservability of Issuers {#privacy-issuer}
```suggestion
## Limiting issuers observability of token verification {#privacy-issuer}
```

2024-03-04 06:07 UTC, tplooker approved these changes

2024-03-04 06:08 UTC, merged